### ISSUE TITLE
ed25519 key needs passphrase

### ISSUE THREAD

**Issue by dopaminereceptionist** [cornfeedhobo/ssh-keydgen#1]
I'm able to generate keys just fine with this. However, if the key is on a host it seems to need a passphrase. I try to give it the one I created the key with, but no luck.

Could you point me in the right direction? Would like to use this without the ssh key agent.

**Comment by cornfeedhobo** [comment]
@dopaminereceptionist I will try and get to this soon.

**Comment by dopaminereceptionist** [comment]
Thanks!

Looking into this more, any 32 byte value should be a valid ed25519 key. I think using the passphrase as an entropy seed might end up weaking the crypto. Maybe you could do a pdkf function and then use that as the ed25519 private key?

**Comment by dopaminereceptionist** [comment]
Hi!

Have you had a chance to look into this?

**Comment by cornfeedhobo** [comment]
I have scheduled time to look at this coming weekend, hopefully that will stay on track.

**Comment by cornfeedhobo** [comment]
@dopaminereceptionist okay looking at this finally. Indeed, looks like you have identified two important issues. I've fixed the entropy generation, just looking into issue of the key being encrypted. It shouldn't be, but I was able to replicate the issue.

**Comment by cornfeedhobo** [comment]
@dopaminereceptionist To address your question about crypto; what you have described is being done, where iteratively hashed versions of the password are used to seed the pbkdf, and, in turn, seed the generation of the ssh keys. I am still looking into the issue with ed25519. Frankly, I'm not sure why it is being marshaled this way.

**Comment by cornfeedhobo** [comment]
@dopaminereceptionist I've been writing some new tests and looking at changing some stuff around. I have narrowed down the exact cause here, and will push a fix soon. After pushing a fix, I'm also going to change the deterministic seeder to be a bit stronger and use Argon2 instead of scrypt. Stay posted.

**Comment by dopaminereceptionist** [comment]
Excellent! Thank you!!
